### ISSUE TITLE
trying to implement OCPP to real charger

### ISSUE THREAD

**Issue by vagio** [mobilityhouse/ocpp#419] opened 2023-02-15 10:25 UTC
Hello i tried to connect to an ABB AC Terra Wallbox charger. On its URL field i set ws://<my_ip>:8080 but it didn't connect to my pc. 
Below is some part of my code

```
server = await websockets.serve(
        on_connect,
        '0.0.0.0',
        8080,
       
        subprotocols=['ocpp1.6'],
       
    )
``` 

```
charge_point_id = path.strip('/')#'TACW2245120T0002'#
    cp = ChargePoint(charge_point_id, websocket)


    console_task = asyncio.create_task(console(cp))

    await cp.start()

    await console_task

async def console(cp):
    try:
        logging.info("Started console")
.....
```
If it works properly i have to see Started console at my console. Is there a problem with my code or maybe it is a firewall issue ?

**Comment by OrangeTux** [comment] 2023-02-15 12:16
You're assumption is not correct. `await cp.start()` 'blocks' until connection is cut by the charger or some other exception is raised. 
If you want to run asyncio tasks in parallel you should use `asyncio.gather()` or `asyncio.wait()`

**Comment by vagio** [comment] 2023-02-15 13:35
> ~~You're assumption is not correct. `await cp.start()` 'blocks' until connection is cut by the charger or some other exception is raised. 
> 
> If you want to run asyncio tasks in parallel you should use `asyncio.gather()` or `asyncio.wait()`~~
> 
> 
> 
> I answered to quickly. The code seems fine. 

So maybe it's a firewall problem ? Server is running on my laptop

**Comment by ndh5188** [comment] 2023-02-19 01:52
I have recently tried to connect to a ENEL juice pump using the example central system code using 1.6j. When I tried to connect to it I got this error. 

  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1511, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 10049] error while attempting to bind on address ('0.0.0.0', 9000): the requested address is not valid in its 
context.

Im fairly new to coding so Im not sure what the problem is. Ive connected to a simulated charger and the code worked just fine. Please let me know if you have any new information on your problem. Thank you.

**Comment by Jared-Newell-Mobility** [comment] 2023-11-13 10:28
So what this is presenting you is an operating system error. After a quick search, there appears to be lots of discussion around causes for Windows [Errno 10049]  - as this is outside the scope of this library and the age of the request, I'll close this issue for now.

**Closed by Jared-Newell-Mobility** 2023-11-13 10:28 UTC
Labels: question
