### ISSUE TITLE
OCPP16 - GetConfiguration documentation

### ISSUE THREAD

**Issue by zsteketee** [mobilityhouse/ocpp#469] opened 2023-08-30 06:04 UTC
Hello,
I'm working on an implementation of the OCPP python library in a project of mine, however when i try to implement the getConfiguration functionality it keeps crashing, probably either due to missunderstandings or due to the lack of documentation, i'm not sure -

Maybe i'm looking over something but i haven't found a solid piece of advice in the last 2 weeks working on this function.
So - Receiving the getConfiguration request from the central station works (backoffice in my case)
but then responding as the charging station doesn't work due to JSON parsing issues.

I've tried all sorts of variations when making a getConfiguration respondse payload, but thus far without succes.

Thank you all in advance and if there's any questions please let me know,

Happy Coding,
Z. Steketee

**Comment by OrangeTux** [comment] 2023-08-30 10:17
>  but then responding as the charging station doesn't work due to JSON parsing issues.

Please provide the logs around this error and the original message causing these errors.

**Comment by zsteketee** [comment] 2023-08-30 13:54
I've managed to work around the issue to catch it right before the websocket gets told to send a message - and then wrote up my own parser for that specific function.

But a similar issue appears when trying to work with ChangeConfiguration - especially the call_result handling thereof.

Here's what i get when i perform the following codesnippit:

```
@on(Action.ChangeConfiguration)
    async def handle_change_configuration(self, *args, **kwargs):
        print(f"ChangeConfiguration, Backoffice wants to change our parameters...\nArgs: {args}, Kwargs: {kwargs}")
        if kwargs["key"] in self.parameters:
            #confirm if this is legal...
            if ("MAX" in kwargs["key"].upper() and int(kwargs["value"]) <= self.hardLimits[kwargs["key"]]) or ("MIN" in kwargs["key"].upper() and int(kwargs["value"]) >= self.hardLimits[kwargs["key"]]): #VALUE WITHIN BOUNDS
                self.parameters[kwargs["key"]]["value"] = int(kwargs["value"])
                request = call_result.ChangeConfigurationPayload(ConfigurationStatus.accepted)
                await self.call(request)
```

My terminal: (i changed a value using the backoffice) ->
```
cp.start() [DEBUG] -> While True, [3]
cp.start() >> Message [SPDC00000001]: [2,"f1c8bf8b-6bb7-4d2b-882b-3699371c5dc3","ChangeConfiguration",{"key":"AcceptAllCards","value":"1"}]
---


ocpp >> messages.py:
unpack() [DEBUG] -> message: [2, 'f1c8bf8b-6bb7-4d2b-882b-3699371c5dc3', 'ChangeConfiguration', {'key': 'AcceptAllCards', 'value': '1'}]

route_message() [DEBUG] -> message_type_id: 2
---


ocpp >> _handle_call()
[DEBUG] - PRE HANDLE - Message: <Call - unique_id=f1c8bf8b-6bb7-4d2b-882b-3699371c5dc3, action=ChangeConfiguration, payload={'key': 'AcceptAllCards', 'value': '1'}>

_handle_call() [DEBUG] -> Message telementry:
action: ChangeConfiguration,
handlers: {'_skip_schema_validation': False, '_on_action': <bound method ChargePoint.handle_change_configuration of <ocppBackOffice.ChargePoint object at 0x0000019989375550>>},
payload (snakecase): {'key': 'AcceptAllCards', 'value': '1'},
handler["_on_action"]: <bound method ChargePoint.handle_change_configuration of <ocppBackOffice.ChargePoint object at 0x0000019989375550>>,
ChangeConfiguration, Backoffice wants to change our parameters...
Args: (), Kwargs: {'key': 'AcceptAllCards', 'value': '1'}
Error while handling request '<Call - unique_id=f1c8bf8b-6bb7-4d2b-882b-3699371c5dc3, action=ChangeConfiguration, payload={'key': 'AcceptAllCards', 'value': '1'}>'
Traceback (most recent call last):
  File "C:\Users\z.steketee\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ocpp\messages.py", line 198, in validate_payload 
    validator.validate(message.payload)
  File "C:\Users\z.steketee\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\jsonschema\validators.py", line 435, in validate 
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('status' was unexpected)

Failed validating 'additionalProperties' in schema:
    {'$schema': 'http://json-schema.org/draft-04/schema#',
     'additionalProperties': False,
     'properties': {'key': {'maxLength': 50, 'type': 'string'},
                    'value': {'maxLength': 500, 'type': 'string'}},
     'required': ['key', 'value'],
     'title': 'ChangeConfigurationRequest',
     'type': 'object'}

On instance:
    {'status': <ConfigurationStatus.accepted: 'Accepted'>}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\z.steketee\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ocpp\charge_point.py", line 300, in _handle_call 
    response = await response
               ^^^^^^^^^^^^^^
  File "C:\Users\z.steketee\Desktop\programming\ocpp-lib-test\ocppBackOffice.py", line 69, in handle_change_configuration
    await self.call(request)
  File "C:\Users\z.steketee\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ocpp\charge_point.py", line 374, in call
    validate_payload(call, self._ocpp_version)
  File "C:\Users\z.steketee\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ocpp\messages.py", line 203, in validate_payload 
    raise FormatViolationError(details={"cause": e.message})
ocpp.exceptions.FormatViolationError: FormatViolationError: Payload for Action is syntactically incorrect or                           structure for Action, {'cause': "Additional properties are not allowed ('status' was unexpected)"}
ocpp >> _send() -> message: [4,"f1c8bf8b-6bb7-4d2b-882b-3699371c5dc3","FormatViolation","Payload for Action is syntactically incorrect or                           structure for Action",{"cause":"Additional properties are not allowed ('status' was unexpected)"}]
cp.start() [DEBUG] -> While True, [4]
```

**Comment by zsteketee** [comment] 2023-09-04 13:25
Any updates?

I've been looking into these schema's - and i don't exactly understand where and why these are creating an issue, as when manually writing to the backoffice works flawlessly.
However it's kind of overkill to have to write work-arounds for each ocpp core function,
Especially TriggerMessages, These are even near-impossible to manage to make do with just work-arounds due to their complex nature...

Sincerely,
Z. Steketee

**Comment by proelke** [comment] 2023-09-04 13:42
From your logs:

Failed validating 'additionalProperties' in schema:
    {'$schema': 'http://json-schema.org/draft-04/schema#',
     'additionalProperties': False,
     'properties': {'key': {'maxLength': 50, 'type': 'string'},
                    'value': {'maxLength': 500, 'type': 'string'}},
     'required': ['key', 'value'],
     'title': 'ChangeConfigurationRequest',
     'type': 'object'}

On instance:
    {'status': <ConfigurationStatus.accepted: 'Accepted'>}

A ChangeConfigurationRequest is being sent with a key in the payload called
status, which is invalid as specified by the schema. Only the key "key" is
allowed. The response message does have a status key in the payload. You
are validating a message that more conforms to
a ChangeConfigurationResponse and trying to validate it against the
ChangeConfigurationRequest schema.

**Comment by proelke** [comment] 2023-09-04 13:55
Looking at the code you provided:

```
@on(Action.ChangeConfiguration)
    async def handle_change_configuration(self, *args, **kwargs):
        print(f"ChangeConfiguration, Backoffice wants to change our parameters...\nArgs: {args}, Kwargs: {kwargs}")
        if kwargs["key"] in self.parameters:
            #confirm if this is legal...
            if ("MAX" in kwargs["key"].upper() and int(kwargs["value"]) <= self.hardLimits[kwargs["key"]]) or ("MIN" in kwargs["key"].upper() and int(kwargs["value"]) >= self.hardLimits[kwargs["key"]]): #VALUE WITHIN BOUNDS
                self.parameters[kwargs["key"]]["value"] = int(kwargs["value"])
                request = call_result.ChangeConfigurationPayload(ConfigurationStatus.accepted)
                await self.call(request)

```
The issue is you are using `await self.call(request)` when you need to return a call result. This example shows you how the code should be written: https://github.com/mobilityhouse/ocpp/blob/master/examples/v16/central_system.py#L25-L33

> there's not that much documentation on chargepoint methods for handling requests and respondses.

If you feel the documentation on the library is not sufficient, I would suggest you open a PR and contribute documentation to improve the library for everyone.

**Comment by zsteketee** [comment] 2023-09-05 06:17
> 

thanks! i'll see what i can do when i have the time
Hopefully i'll be able to resolve some of my problems now. Thanks for the information and the help :)

I'll update this thread if i make any progression on additional documentation - please bare with me as this is the first public repo collab i've done in my carreer (junior of the juniors)

**Comment by Jared-Newell-Mobility** [comment] 2023-11-15 13:46
Appears to be resolved - will close this for now.

**Closed by Jared-Newell-Mobility** 2023-11-15 13:46 UTC
Labels: good first issue
